apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iamdb-pvc
  namespace: nodc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: $IAMDB_SIZE
  storageClassName: $STORAGE_CLASS
  volumeMode: Filesystem
